@baseUrl = http://localhost:3333

### Get All user
@name = get-all-user
GET {{ baseUrl }}/user/all
Accept: application/json


### POST Create user
POST {{ baseUrl }}/user/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@fs3.com",
    "zipcode": "12345678",
    "address": "Rua dos bobos",
    "whatsapp": "123456789",
    "password": "123456"
}


### POST Authe user
POST {{ baseUrl }}/user/auth
Content-Type: application/json

{
    "email": "john@fs3.com",
    "password": "123456"
}


### POST Create product
POST {{ baseUrl }}/product/create
